### ISSUE TITLE
GNOME 46 support

### ISSUE THREAD

**Issue by Striffly** [EliverLara/Otis#13]
Hello,

I've encountered numerous errors while using GNOME 46, especially when receiving a notification and hovering over it. Do you have plans to provide fixes to support this version?

Thank you (and also thanks for your awesome work)

**Comment by EliverLara** [comment]
Hi, Could you provide a screenshot please?

**Comment by Striffly** [comment]
I got this when hovering notification :
![Screenshot from 2024-04-13 04-22-03](https://github.com/EliverLara/Otis/assets/13284087/bf6709af-ac13-40f4-955a-cce0d0b2fcc8)


All extensions are disabled except User Themes.
Theme is set with Tweaks & libadwaita-theme-changer.
I use `notify-send foo bar` to test notifications.

**Comment by EliverLara** [comment]
THanks for reporting and for your help! I fixed it.
