### ISSUE TITLE
Include the wallpaper

### ISSUE THREAD

**Issue by joes-mama** [EliverLara/Otis#15]
Please _please_ include the file of the forest wallpaper. It's shown in this screenshot from gnome-look.org and I can't find the same edited one _anywhere_ on the internet! Thanks for a great theme!
![image](https://github.com/EliverLara/Otis/assets/135121377/50724c85-f295-47a6-8f09-4202b1a7ea1d)

**Comment by EliverLara** [comment]
Hi, [here is](https://imgur.com/NuFVbLW) the wallpaper I use :)

**Comment by joes-mama** [comment]
Thank you so much man! I can't get enough of this theme it is so good
