### ISSUE TITLE
Theme didnt apply to the following elements

### ISSUE THREAD

**Issue by lmajhi** [EliverLara/Otis#2]
Hi,
On applying the catrina theme, the following elements didnt reflect change. 
Change you please point out, what could be the reason and how to mitigate it.
![Screenshot_Desktop](https://user-images.githubusercontent.com/30113190/139518956-ea984f79-8cc2-41e0-8e67-0047f48f37dc.png)
![Screenshot from 2021-10-30 08-14-47](https://user-images.githubusercontent.com/30113190/139518967-c9086a6e-94e2-4031-8891-996354cf8728.png)

**Comment by EliverLara** [comment]
Hi, It's fixed with latest commit.
