### ISSUE TITLE
Dark mode not working

### ISSUE THREAD

**Issue by Izzami** [EliverLara/Otis#3]
Hi I have Pop!_Os, when I set the theme it works, but the system default applications like the notification panel or the shutdown keys remain white.
When I try to switch back to dark mode from the settings, the default Pop! _Os theme comes back on

![Schermata del 2021-12-09 22-53-49](https://user-images.githubusercontent.com/39417344/145482025-1823dfd4-0c42-44ff-b9d4-9a27746b79bb.png)

![Schermata del 2021-12-09 22-54-06](https://user-images.githubusercontent.com/39417344/145482080-a78eff8e-6d37-44d0-b372-c3d112458046.png)

.

**Comment by EliverLara** [comment]
Hi could you test if renaming the theme's folder fro `'Otis'` to `'Otis-dark'` fixes this issue, please?

**Comment by Izzami** [comment]
> Owner

Yoo, It works.
Thanks you so much.
