### ISSUE TITLE
theme not working .. 

### ISSUE THREAD

**Issue by reskaddse** [EliverLara/Otis#4]
![Screenshot from 2022-02-26 10-43-54](https://user-images.githubusercontent.com/100458091/155829872-af6f8dc5-bcda-4039-9be7-a97c87718619.png)
theme not working for application panel and also not working for unity panel ... in unity desktop in ubuntu 21.10..   can you please fix it.. or can you tell me how to fix it ... your help will really be appreciated ...
![Screenshot from 2022-02-26 10-45-17](https://user-images.githubusercontent.com/100458091/155829878-6639a9a2-9773-4ae6-8a6d-cbb8bef152d1.png)

**Comment by EliverLara** [comment]
This theme does not provide support for unity, sorry.
