### ISSUE TITLE
Artifact on Nautilus Window Border

### ISSUE THREAD

**Issue by Joomsy** [EliverLara/Otis#7]
There's a little artifact hanging off the edge of Nautilus windows that doesn't appear on any other GTK applications:

![Screenshot from 2022-04-09 16-51-34](https://user-images.githubusercontent.com/103767404/164814021-2485dcf8-cadf-4b81-b3be-2b62785f7513.png)

As mentioned, this artifact doesn't appear to be present with any other application.

- Distro: Pop_OS 21.10
- DE: GNOME 40.4.0 on Wayland
- Using latest commit for Forest ([3441f4c](https://github.com/EliverLara/Otis/commit/3441f4c5691dd6711ef7989521acb9ba3163a2b5))

**Comment by EliverLara** [comment]
That was fixed! :)
